import { CampaignData } from "./type";

const dummyCampaigns: CampaignData[] = [
  {
    id: "1",
    email: "student1@example.com",
    title: "Scholarship for New Students",
    name: "John Doe",
    admission_proof_url: "https://example.com/admission-proof/1",
    university_name: "University of Example",
    matric_number: "12345678",
    course_of_study: "Computer Science",
    year_of_entry: 2023,
    student_image_url: "https://example.com/images/student1.jpg",
    student_result_image_url: "https://example.com/results/student1.jpg",
    funding_reason: "To support my studies in computer science.",
    project_link: "https://example.com/project/1",
    goal: 5000,
    start_at: new Date("2023-09-01"),
    end_at: new Date("2024-09-01"),
    status: "pending",
    created_at: new Date("2023-08-01"),
    updated_at: new Date("2023-08-10"),
    authorized: false,
  },
  {
    id: "2",
    email: "student2@example.com",
    title: "Engineering Scholarship",
    name: "Alice Smith",
    admission_proof_url: "https://example.com/admission-proof/2",
    university_name: "Tech University",
    matric_number: "23456789",
    course_of_study: "Mechanical Engineering",
    year_of_entry: 2022,
    student_image_url: "https://example.com/images/student2.jpg",
    student_result_image_url: "https://example.com/results/student2.jpg",
    funding_reason: "To fund my research project in mechanical engineering.",
    project_link: "https://example.com/project/2",
    goal: 10000,
    start_at: new Date("2022-10-01"),
    end_at: new Date("2023-10-01"),
    status: "approved",
    created_at: new Date("2022-09-01"),
    updated_at: new Date("2022-09-15"),
    authorized: true,
  },
  {
    id: "3",
    email: "student3@example.com",
    title: "Arts Grant for Creative Projects",
    name: "Bob Johnson",
    admission_proof_url: "https://example.com/admission-proof/3",
    university_name: "Creative Arts University",
    matric_number: "34567890",
    course_of_study: "Fine Arts",
    year_of_entry: 2021,
    student_image_url: "https://example.com/images/student3.jpg",
    student_result_image_url: "https://example.com/results/student3.jpg",
    funding_reason: "To fund my art exhibition and projects.",
    project_link: "https://example.com/project/3",
    goal: 3000,
    start_at: new Date("2021-11-01"),
    end_at: new Date("2022-11-01"),
    status: "rejected",
    created_at: new Date("2021-10-01"),
    updated_at: new Date("2021-10-05"),
    authorized: false,
  },
  {
    id: "4",
    email: "student4@example.com",
    title: "Postgraduate Research Funding",
    name: "Emily Brown",
    admission_proof_url: "https://example.com/admission-proof/4",
    university_name: "Research University",
    matric_number: "45678901",
    course_of_study: "Physics",
    year_of_entry: 2020,
    student_image_url: "https://example.com/images/student4.jpg",
    student_result_image_url: "https://example.com/results/student4.jpg",
    funding_reason: "To support my research on quantum mechanics.",
    project_link: "https://example.com/project/4",
    goal: 15000,
    start_at: new Date("2020-12-01"),
    end_at: new Date("2021-12-01"),
    status: "approved",
    created_at: new Date("2020-11-01"),
    updated_at: new Date("2020-11-10"),
    authorized: true,
  },
];

export default dummyCampaigns;
